# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c9844259acbe211aa05df749cb361dae90ef709325c1939eb7a3a09d42557b65782118484ca992c4101a8c2a0916d5d8ec3ad4450b5d091de423f05a10ef8a7

test:
  secret_key_base: be1e1080d3becdc1fe9c8f625eef93620cb980032e2264dd0164c90ae08af8d4f6513241b051a3c69cff1abd338fd5e03d22fc6e0540be6bab511755e276e2f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
